project_id: "917965"
base_path: .
base_url: "https://api.crowdin.com"
preserve_hierarchy: true

files:
  - source: /locales/en/extension.json
    translation: /locales/%locale%/extension.json

  - source: /locales/en/server.json
    translation: /locales/%locale%/server.json

  - source: /locales/en/shared.json
    translation: /locales/%locale%/shared.json
